name: Docker Image CI

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: roxsross12
  VERSION: 1.0.0

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: donde estoy
      run: pwd
    - name: listado 
      run: ls -lrt
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - name: Build the Docker image app
      run: |
        cd src/app
        docker build -t frontend:$VERSION .
        docker images
        docker tag frontend:$VERSION $REGISTRY/frontend:$VERSION
        docker push $REGISTRY/frontend:$VERSION
    - name: Build the Docker image consumer
      run: |
        cd src/consumer
        docker build -t consumer:$VERSION .
        docker images
        docker tag consumer:$VERSION $REGISTRY/consumer:$VERSION
        docker push $REGISTRY/consumer:$VERSION
